apiVersion: v1
kind: ConfigMap
metadata:
  name: hookrail-config
  namespace: hookrail
data:
  REDIS_ADDR: "redis:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  HOOKRAIL_ADMIN_URL: "http://admin:8082"
  HOOKRAIL_INGRESS_URL: "http://api:8080"
