version: "2"
linters:
  default: standard
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
linters-settings: {}
run:
  build-tags:
    - integration
    - e2e
