---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-worker-to-test-receiver
  namespace: hookrail
spec:
  podSelector:
    matchLabels:
      app: test-receiver
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: worker
      ports:
        - port: 9090
